### ISSUE TITLE
spm v3.6.0 unknown option `--with-deps'

### ISSUE THREAD

**Issue by nimoc** [spmjs/docs#2]
https://github.com/spmjs/spm/issues/1227#issuecomment-81733765

afc163 commented on 16 Mar

> 使用此方式我需要将每个所需模块都执行一次 spm build -O ../../../spm 是否有快捷方法可以一次性将 spm_modules/ 所有文件全部 build ？
> 目前可以使用 spm build --with-deps 来打包依赖模块，同样会输出到 dist 目录中。

```
spm install dzoom
cd spm_modules/dzoom/0.0.1/
spm build --with-deps
    error: unknown option `--with-deps'
```

**Comment by sorrycc** [comment]
看下 3.6 的注意点：https://github.com/spmjs/docs/blob/master/misc/upgrade-to-3.6.md。

cmd 的打包方式不再内置，提取到 spm-sea 了。
