### ISSUE TITLE
请求更新文档

### ISSUE THREAD

**Issue by walkwolf** [spmjs/docs#25]
spm -v
3.9.0-beta3
spm init 无命令，请求更新文档

**Comment by chencl2bj** [comment]
这工程已改已经放弃维护了

**Comment by chencl2bj** [comment]
现在已经没有init命令了  你可以自己在工程下面建立package.json文件,然后跑spm build就行，package.json文件格式我写在下面
{
  "name": "818",
  "version": "1.0.0",
  "description": "818 peoject",
  "main": "index.js",
  "author": "leonC",
  "license": "ISC",
  "spm": {
    "main": "index.js"
  },
  "keywords": [
  ]
}

**Comment by walkwolf** [comment]
收到

**Comment by popomore** [comment]
https://github.com/spmjs/spm-init
