### ISSUE TITLE
spm build --watch 速度疑问

### ISSUE THREAD

**Issue by nimoc** [spmjs/docs#3]
先赞一个这个文档项目，更简单易懂了。

---

```
{
  "spm": {
    "output": [
      "*.js"
    ],
    "dependencies": {
      "jquery": "~2.1.3"
    }
  }
}
```

```
$ spm build --watch
```

修改 a.js 会出现如下消息

```
 generated: a.js 83.17kB
          build: done
          build: compile
      generated: b.js 83.17kB
      generated: index.js 83.17kB
      generated: a.js 83.17kB
          build: done
          build: compile
      generated: b.js 83.17kB
      generated: index.js 83.17kB
      generated: a.js 83.17kB
          build: done
```

我如何控制修改时只build当前 a.js 文件。

`spm build --watch` 的调试速度比 `spm server` 慢很多。可以通过某种方式提速么？

再请教一个问题：

```
$ spm build index.js index.html
```

我能用 gulp 调用 `spm build index.js index.html` 命令么？

我可能需要 build 完了会接着做一些其他操作。

spm 提供一些对外的接口，利用这些接口与其他模块结合。构建一整套的前端工作流程。

```
var spm = require('spm')
spm.build('index.js').on('done',function(){
// .. somecode
})
```

**Comment by sorrycc** [comment]
- `spm build --watch` 慢很多主要是因为多做了压缩这一步，可以试下 `spm build --watch --debug`
- gulp 调用应该没问题吧

**Comment by sorrycc** [comment]
接口是需要再整理下，现在可以通过下面的方式使用：

``` javascript
var build = require('spm-webpack').build;
build(args, function(err, stats){
  // .. some code
});
```

例子：https://github.com/spmjs/spm-webpack/blob/master/cli.js#L77

**Comment by nimoc** [comment]
:+1:  收到，感谢。

期待 spm 3.6 的接口文档

---

我可以直接向这个项目 PR 一些项目开发教程么？方便我们公司的同事使用

**Comment by sorrycc** [comment]
可以啊，pr 上来看下。

2015-04-22 10:57 GMT+08:00 NimoChu notifications@github.com:

**Comment by nimoc** [comment]
:ok_hand:  下班了 PR
