### ISSUE TITLE
关于 hash 

### ISSUE THREAD

**Issue by nimoc** [spmjs/docs#5]
> 配置输出文件名是否带 hash 后缀。

我开启了 `hash` 最终生成了 `index-2b7f66baa43cdf4d6016.js` 文件。

但是没有生成类似 `map.json` 的文件

```
// map.json
{
    "file":{
      "index.js": "index-2b7f66baa43cdf4d6016.js"
    }
}
```

**Comment by nimoc** [comment]
可否使用 spm 的hash 配置 完成 fis 能实现的非覆盖式发布

![https://raw.githubusercontent.com/fouber/blog/master/assets/resource/14.png](https://raw.githubusercontent.com/fouber/blog/master/assets/resource/14.png)

**Comment by sorrycc** [comment]
提供 map.json 应该就可以了吧?

**Comment by nimoc** [comment]
```
OS.X 10.10
spm 3.6.0
node v0.12.1
```

package.json

```
{
  "spm": {
    "main": "index.js",
    "build":{
      "hash":true
    }
  }
}
```

```
spm build
```

只生成了 `dist/index-c7003122f953dfc45f4a.js`

**Comment by sorrycc** [comment]
现在没有 spm 生成 map.json，我们这边业务里是由另一个环节生成的。如果要 `map.json`，建议自己写个脚本，在 spm build 完之后调用下。
